services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "4533:4533"
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
    volumes:
      - ./music:/music:ro
      - navidrome_data:/data
    restart: unless-stopped

volumes:
  navidrome_data:
